### ISSUE TITLE
Should I use this code?

### ISSUE THREAD

**Issue by paluh** [clappr/click-to-pause-plugin#1]
Sorry if this is stupid question, but I'm not sure why there is this plugin repository and there is the same plugin in main clappr repo under `plugins/click_to_pause`? Am I missing something?

I have additional question - I want to use this plugin in my custom build (with webpack) how should I import this module?

**Comment by leandromoreira** [comment]
Hi @paluh  @clappr/core is rethinking the module system we developed for clappr, one of the ideas is to break it down in small plugins I think this is part of this effort, so don't mind for while to use this code, isn't that right @clappr/core ?

**Comment by paluh** [comment]
Hi @leandromoreira and thanks for quick answer!

I'm trying to write Purescript wrapper around clappr: https://github.com/paluh/purescript-clappr and I'm just not sure how should I access/import plugins modules from clappr in my js modules.

I know can use `require('clappr')`, but what about modules from `plugins` dir?

**Comment by leandromoreira** [comment]
@vagnervjs @joaopaulovieira @towerz can help you :) (maybe in weekdays though ;P)

**Comment by paluh** [comment]
Sure! Thanks!

**Comment by paluh** [comment]
I'm not sure if it's good place to ask this question:

Should maybe I just provide a pull request to clappr repo with changes in `main.js`:

    import ClickToPausePlugin from 'plugins/click_to_pause'

and add it to main module exports to get access to `Clappr.ClickToPausePlugin`?

**Comment by towerz** [comment]
@paluh sorry for taking some long, I've been away for a couple weeks. Actually, this repo will be used soon by the main Clappr project, but you shouldn't use it for now. We're still in the process to split the plugins from the Clappr core so everyone has access to the plugins, as well as avoid including unused ones.

About the `ClickToPausePlugin`, I think it was overlooked. Perhaps you should create the PR you suggested. Thanks!

**Comment by paluh** [comment]
Thanks for informative response @towerz!

I'm going to provide PR soon. I'm closing this as everything is clear now.
